### ISSUE TITLE
n你好，这个被禁，能改成调取系统自带的按键吗？？？vbs？

### ISSUE THREAD

**Issue by chexiansheng** [hs-CN/auto_fishing_py#1]
这个可以可以改成vbs之类的按键吗

**Comment by hs-CN** [comment]
这个我不确定。
我自己估计大概率是被举报的，我做好后，在暗月岛连续调了2个晚上。行为异常太明显了。
暴雪本身应该是无法检测是否有运行什么脚本的。
不过，如果有特别的记录的话，暴雪应该是可以看到底层的鼠标事件的。
我已经用python脚本尽量模拟鼠标移动了，用的是win32api 发出的mouse move事件。
我没接触过vbs，不清楚vbs可以通过什么方式来操作鼠标。
如果要继续改进，最好是能在设备层面模拟，注册虚拟设备什么的。[也许这个可以](https://github.com/obv-mikhail/inputbot)

**Comment by chexiansheng** [comment]
大佬 方便联系一下吗？可以有偿，这个太肝了。。。我掉铜币都要吐了。。。我发你outlook邮箱没有回复，才发的这个。

**Comment by hs-CN** [comment]
> 大佬 方便联系一下吗？可以有偿，这个太肝了。。。我掉铜币都要吐了。。。我发你outlook邮箱没有回复，才发的这个。

你会python吗，我所有的代码都在这里了，用的yolo目标检测，数据收集，数据标记，训练，模型测试，等都有

**Comment by chexiansheng** [comment]
我不太会。。。主要是小白。。。来这里就是跟大佬学习。。。非程序员。。。个人玩家。。。求大佬指点 有偿有偿

**Comment by hs-CN** [comment]
> 我不太会。。。主要是小白。。。来这里就是跟大佬学习。。。非程序员。。。个人玩家。。。求大佬指点 有偿有偿

这个方法需要搜集数据训练模型，训练模型想要比较好的显卡(支持cuda的显卡)，你电脑显卡怎么样

**Comment by chexiansheng** [comment]
方便留个联系方式吗。我邮箱发你





------------------ 原始邮件 ------------------
发件人: shuai.huang ***@***.***&gt;
发送时间: 2024年9月12日 23:14
收件人: hs-CN/auto_fishing_py ***@***.***&gt;
抄送: chexiansheng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hs-CN/auto_fishing_py] n你好，这个被禁，能改成调取系统自带的按键吗？？？vbs？ (Issue #1)





  
。。。我就是普通的笔记本。。。算老式的了。。。
  
那可能不太行

**Comment by hs-CN** [comment]
抱歉

**Comment by hs-CN** [comment]
> 方便留个联系方式吗。我邮箱发你
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: shuai.huang ***@***.***&gt; 发送时间: 2024年9月12日 23:14 收件人: hs-CN/auto_fishing_py ***@***.***&gt; 抄送: chexiansheng ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [hs-CN/auto_fishing_py] n你好，这个被禁，能改成调取系统自带的按键吗？？？vbs？ (Issue #1) 。。。我就是普通的笔记本。。。算老式的了。。。 那可能不太行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

抱歉，issue 我关闭了

**Comment by chexiansheng** [comment]
没事。你这个有点高级…… 大哥能简单帮忙做一个吗。 话说我用的都是直接用python打开ide运行。你用哪个运行？vscode吗





------------------ 原始邮件 ------------------
发件人: shuai.huang ***@***.***&gt;
发送时间: 2024年9月12日 23:20
收件人: hs-CN/auto_fishing_py ***@***.***&gt;
抄送: chexiansheng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hs-CN/auto_fishing_py] n你好，这个被禁，能改成调取系统自带的按键吗？？？vbs？ (Issue #1)





 
抱歉

**Comment by hs-CN** [comment]
> 没事。你这个有点高级…… 大哥能简单帮忙做一个吗。 话说我用的都是直接用python打开ide运行。你用哪个运行？vscode吗

有兴趣可以学习下python，简单的，还是挺有帮助的。用什么方式运行都一样，其实都是在一个控制台终端运行显示。只是一个是python自带的可以编辑调试的，一个是vscode编辑器集成的，直接打命令运行也都是一样的效果

**Comment by chexiansheng** [comment]
好的好的。 谢谢。





------------------ 原始邮件 ------------------
发件人: shuai.huang ***@***.***&gt;
发送时间: 2024年9月12日 23:26
收件人: hs-CN/auto_fishing_py ***@***.***&gt;
抄送: chexiansheng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hs-CN/auto_fishing_py] n你好，这个被禁，能改成调取系统自带的按键吗？？？vbs？ (Issue #1)





  
没事。你这个有点高级…… 大哥能简单帮忙做一个吗。 话说我用的都是直接用python打开ide运行。你用哪个运行？vscode吗
  
有兴趣可以学习下python，简单的，还是挺有帮助的。用什么方式运行都一样，其实都是在一个控制台终端运行显示。只是一个是python自带的可以编辑调试的，一个是vscode编辑器集成的，直接打命令运行也都是一样的效果
